import type { Subgraph } from "./graph.js";
import type { DetectionFinding } from "./types.js";
import { getProvider } from "./providers/index.js";

// The narrative is GENERATED by the model, grounded in the shared entity graph.
// The graph is the guardrail: the model may only connect entities that exist as
// nodes, which is what makes this "graph-grounded" rather than free narration.
const NARRATIVE_SYSTEM_PROMPT = [
  "You are a threat-hunting analyst writing the campaign narrative for one investigation.",
  "You are given (1) the structured DetectionFindings produced by the detection skills and (2) the shared entity graph (hosts, users, processes, IPs, candidates) that links them.",
  "Write a concise campaign narrative explaining how the findings connect THROUGH the shared graph entities and edges.",
  "Grounding rules:",
  "- Only name hosts, users, processes, IPs, or candidates that appear as nodes in the supplied graph. Do not introduce any entity that is not in the graph.",
  "- Every assertion must trace to a supplied finding or a graph edge. Do not invent verdicts, scores, or evidence.",
  "- Where findings are inconclusive, say so plainly rather than overstating the campaign.",
  "Return the narrative as a few short Markdown paragraphs.",
].join("\n");

export async function synthesizeNarrative(
  findings: readonly DetectionFinding[],
  graph: Subgraph,
): Promise<string> {
  if (!findings.length) return "No findings were available to synthesize.";

  const provider = getProvider();
  const userPrompt = [
    "## DetectionFindings",
    JSON.stringify(findings, null, 2),
    "",
    "## Shared Entity Graph",
    "Nodes:",
    ...graph.nodes.map((node) => `- ${node.type}: ${node.label} (${node.id})`),
    "",
    "Edges:",
    ...graph.edges.map((edge) => `- ${edge.source} --${edge.label}--> ${edge.target}`),
    "",
    "Write the campaign narrative now, connecting the findings through these shared entities.",
  ].join("\n");

  const result = await provider.invoke({
    systemPrompt: NARRATIVE_SYSTEM_PROMPT,
    userPrompt,
  });
  return result.text;
}
